### ISSUE TITLE
[Android Bootcamp] Assignment 1: Popular Photo - Ready for Review

### ISSUE THREAD

**Issue by sbharech** [sbharech/PopularPhotos#2]
My app is complete and ready for review. Kindly review it and let me know your comments. /cc @codepathreview @codepath

-- Suraj Bharech (observer)

I have some additional questions:
1. If we want to show certain piece of info conditionally (let's say view count/comment count only if they are non zero), we can hide the view by making it invisible. But still it takes up the space. For this, do we have to have 2 layout or we can achieve it programatically.
2. If network error happens, the list is empty. After that pull to refresh is not working.

**Comment by nesquena** [comment]
> If we want to show certain piece of info conditionally (let's say view count/comment count only if they are non zero), we can hide the view by making it invisible. But still it takes up the space. For this, do we have to have 2 layout or we can achieve it programatically.

Use the [Visibility.GONE instead of invisible](https://github.com/codepath/android_guides/wiki/Styling-UI-Screens-FAQ#how-do-i-hide-a-view-at-runtime-or-make-the-view-collapse-within-the-layout) and it works as you want.

> If network error happens, the list is empty. After that pull to refresh is not working.

This is because you need to handle the case that the network request fails in onFailure method. In that case, you need to set refreshing false and potentially do other error handling to ensure the list and refresh aren't in a broken state.

**Comment by sbharech** [comment]
Visibility.GONE solved it. Just wanted to know that when we cache the views using viewholder pattern, we will have to make the view visibile explicitly because it might have made gone previously right? How much performance impact it will have.

Regarding the pull to refresh not working, this is what I did:

1. onFailure method, set the dialog to the user and mark the layout view set refreshing as false. Still after that I am not able to pull. I would really like to know if you have any working piece of code somewhere I can refer to.

**Comment by sbharech** [comment]
/cc @codepathreview @codepath

Visibility.GONE solved it. Just wanted to know that when we cache the views using viewholder pattern, we will have to make the view visibile explicitly because it might have made gone previously right? How much performance impact it will have.

Regarding the pull to refresh not working, this is what I did:

onFailure method, set the dialog to the user and mark the layout view set refreshing as false. Still after that I am not able to pull. I would really like to know if you have any working piece of code somewhere I can refer to.

**Comment by sbharech** [comment]
/cc @codepathreview @codepath

I am yet to receive feedback on my Week1 assignment.

**Comment by nesquena** [comment]
:+1: Looks good! I have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this has given you a first sense of the RelativeLayout which is a very powerful layout system, probably one of the best responsive-first layout systems available across web and mobile platforms. This project also incorporates first introductions to basic networking, image loading and more complex feeds.

I would encourage you to also spend more time in future projects [improving the UI / UX](http://guides.codepath.com/android/Styling-UI-Screens-FAQ) as well by reviewing examples of [good UI design](http://www.android-app-patterns.com/). 

The next project will build on top of the first concepts introduced here and will introduce several new topics.
